### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by chrisnguyn** [AlexTuTruong/i-sell-nails#1]
remembering the acceptance criteria is:

- a web app where i can add a type of nail with price + initial quantity

- i can click on the UI to buy a nail and later sell it for 0.75x its initial price

- if i hover over the 'total' amount (which is a running total of all txns happening) it should give a breakdown of everything that's happened

---

at a glance,

- no demo video / media, i want to see the frontend, are you expecting me to clone the repo and run it myself? also your setup instructions should mention `pip install requirements.txt`, no?

- imo `app/` should be `src/`

- doesn't look like there's an initial quantity on the Nail class

- without seeing the frontend or a screen recording demo it's hard to pinpoint what i want to see more of

- could refer to https://github.com/tarang5757/I-Sell-Hammers/issues the 2 issues i posted to see what problems i had with his repo

**Comment by chrisnguyn** [comment]
your readme.md is really redundant just keep it concise. what it is what it does. what you get out of the box.

```
I Sell Nails

I sell nails is a web application and API which a user can run a nail selling business. <<< where the description already goes

Description: <<< why do you have an extra header

I sell nails is a project I started inspired/suggested by a friend so I can get more full stack experience.  <<< remove

I wanted to have more experience writing full stack applications so I sell nails <<< remove

It uses [FastAPI](https://fastapi.tiangolo.com/) to provide endpoints in which a user can manipulate a database to add, sell and buyback nails <<< this is the only useful piece of information you've really given
```

**Comment by chrisnguyn** [comment]
your buy back is supposed to be 0.75x the original price

i'm a store: i sell it to you for $1, you want to refund it, you only get $0.75

**Comment by chrisnguyn** [comment]
you should keep a running total of how much of something you sold, if i sold 10 of nail#1, i can't "refund" 11. my total also shouldn't go into the negatives.

hovering over the total should produce a running receipt of my total.

```
$0 - opened for business
$1.00 - sold type 'A' for $1.00
$0.25 - refunded type 'A' for $0.75
```

etc.

**Comment by chrisnguyn** [comment]
what is "SKU"?

**Comment by chrisnguyn** [comment]
optionally include an image when adding a nail. this could be a BLOB in your DB

**Comment by chrisnguyn** [comment]
i should be able to update the price of an existing nail.

if i add type A for $3.00

and then i add again, type A, for $4.50, it should reflect on the UI

**Comment by AlexTuTruong** [comment]
Addressed most things here:

* Changed `app/` to `src/`
* Added dummy data population on db creation
* Demo recording has been added to README
* Readme has been condensed to be more concise/less redundant
* Buyback now purchases sold stock back at 0.75x the price sold for
* A ledger now displays the all transaction types which take place and how many of each
* You can now input the same nail type to update the properties of an existing nail


Thanks for the review!
